version: 1.0.0.{build}

configuration: Release

os: Visual Studio 2017

branches:
  only:
    - master

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  TARGET_BUILD_VERSION: '1.2.0'

nuget:
  disable_publish_on_pr: true

before_build:
- dotnet --info
- dotnet restore .\src\ReverseMarkdown.sln

build_script:
- dotnet build .\src\ReverseMarkdown.sln --configuration Release /p:Version=%TARGET_BUILD_VERSION%
  
after_build:
  - dotnet pack .\src\ReverseMarkdown --configuration Release /p:Version=%TARGET_BUILD_VERSION%

test_script:
  - dotnet test .\src\ReverseMarkdown.Test\ReverseMarkdown.Test.csproj --configuration Release

artifacts:
  - path: '**\ReverseMarkdown.*.nupkg' # find all NuGet packages recursively

# deploy:
#  - provider: NuGet
#    api_key:
#     secure: 1XMgADnmiLunXwBT7K0CMDcHyoC5tUFE4Cf+X7VkuzoRZiWnIL2P9mP7oPEtGPHg
#    skip_symbols: true